### ISSUE TITLE
Link colouring for `<a>` tags with subelements

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/website_diff#21]
If you check out https://github.com/joelostblom/viz-oer/tree/407c3267ae5f2a854d029626a2b19fc8d869e4f2 , you'll see that links to changed pages are not coloured properly.

I think it might be because the `<a>` tag has a sub `<span>` tag that overwrites style for the text inside. One possible solution: when colouring links, traverse to the lowest content element and wrap it in a `<span>` or `<div>` or something that adds a particular class. Even better would be to prevent subelements from overriding the `<a>`'s style (to avoid adding extra elements), but I'm not sure that's possible...

**Comment by joelostblom** [comment]
Note that after I switched to use the branch from https://github.com/trevorcampbell/website_diff/pull/18, it seems like links are now colored correctly, although the overall formatting is a bit odd. For an example, see https://joelostblom.github.io/viz-oer/diff29/index.html:

![image](https://github.com/user-attachments/assets/6eac18c0-b1d6-4f05-a3ac-65ff3bda30a5)

This PR https://github.com/joelostblom/viz-oer/pull/29
