### ISSUE TITLE
Changed sections not highlighted in Sphinx and code blocks removed

### ISSUE THREAD

**Issue by joelostblom** [trevorcampbell/website_diff#33]
I have been experimenting a bit more with the altair docs (built via sphinx) and noticed that changed sections/chapters don't seem to be highlighted in the navigation bar. For example, here I have changed things in both the "Parameters, Conditions, & Filter" section and in the "Bindings & Widgets" section, but neither is highlighted:

![image](https://github.com/user-attachments/assets/d30e2232-7f0b-403c-a336-4495c5df51fc)

I also noticed that our gallery examples all had their code removed in the diffed output and I'm not sure why. This is what the diffed page looks like:

![image](https://github.com/user-attachments/assets/05d67f51-b2e3-4fa4-b95b-e13837bc3a3c)

Whereas the actual page looks like this:

![image](https://github.com/user-attachments/assets/e4fa5024-9874-47a0-adfe-6f876c81a705)

I think you can use the procedure in https://github.com/trevorcampbell/website_diff/issues/28#issue-2532393078 to reproduce, just add any change you want directly in the HTML instead of building the docs from rst like i did.

**Comment by briank-git** [comment]
@joelostblom 

I think I fixed the bugs up to and including this one and just cut a release. v0.1.0 is live on PyPi https://pypi.org/project/website-diff/0.1.0/

FYI `cairo` is a new requirement, you may need to install it if it's not included in your distribution.

**Comment by joelostblom** [comment]
Super, thank you!
